language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST=true"
  password:
    secure: RdDd92+zwQbc9hYtPPM5J37U+oc5zIQBVp8j76euSBgNj+yy8rmICfQm4RRbA+vCXlZOGycwusJIMYQGB/yVNqpGtitqRGX86Jkp5z8945JzJZGG5rpsNbh1CmP32QlCzUIDnLaIDoVu1oVFaGo34pSszvCSIyOyo8HacCjhsUhy/mYJbpi7w6AF973397qI97ildo7SVN7Kwv0RNr8vfU2G7JnxDauLkkmdwvvFYP0eFBjiJMP/45U5AUR4jnxZsxXw4V3LzqspgsBn+qJFRJHxaVusDahJqkGlJK5S+21N1k75PwsJWoCvpWAA4KZzw4rej/ImMY60dVMXmEx7UC4xweOsPtkpwJzhkPjrSu2uBJhwGRPzIGZcweuLbzsitocYObgbBI+n+roH9pkyJTMWo+zeRw5sihxOaEqID/zMBJP4gdIk4YdIW/1tPt5z7E5MK4baLZDsIZNILJrzCKpq21RmlyazXf7HA7CJDyvGblT2N/PcTvS3lzmgegvW2EkTCBzlbUqvc+sOmWDObWjBJCXAGdQ2h/q5hbK7YGT3M2+NSZEeXXgxVNG9z1Wqy48ZAzBOl1gtVvBw88ZX0Z7AQGGE7ilGGN1SLhJGgBdeZdkuB21VV8KwQCZRyw7xTZHxnr2AfcacJ7CrjdzHpVVvKuC+qfoYggjoqbxTA2A=
  distributions: "sdist bdist_wheel bdist_egg"


