language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST=true"
  password:
    secure: UxEm8a03Bnc/qFt5e1noekmnxAMbG5D0ODfiD7gXQ3MhFmkOdF6M2Hf4fPyr/lJ/9jZ4HNbcnj9opk48uNBMRlOvyZ7EPK6mTEiH31UHxWvu6f6LrzDnXN6luFkR+xXpONNseOfzam6S3J/41MVfscgAZX46MMXgB38t7RwYZssRX9EbgSW8jkGeRYGcFE364wST0dDHssLJD6uXKGM26nW4Y+uPSr67BTsm5mVgYjz2/kcastS88l0oShSmF/D50eVknXcZYsasa/wbwmz7miErgQNcI3z7vR9ttjNGtONjhk/cHZdAa/Vh3cpy2ftET5FogQUXpeXNLH4deIAY0HQ4tTZ5oyHUdP2rIhxBVNZen+HzOpdiWBGNdaBW40+eAIV/fVkxbwb5/FT0WNH22rXjBcLKpvyfsgMRTIk/K9s6wuydKRxK9cBvd9C2d/DU1hszMikj5SPaVXESzOWETcrXLwU/V30DgRkWSg1xKWkJsUJOny05UEi/LNfkSrZ2rXQgjiNtFjD3owRyF15izG/G2xYVTz+de6J5zrnVrj/FlE3ZOERZ+NSm7oGH00JOLxgxkars87IEXo5XT7/ujN904osJYmdfFQtdHRmWWbXfoWjLu9mHcYEG36PNcaGgmoEVG4+9Ze3q4W/czaUIPx2ltXR/a8x+oxQqYJSWpGw=
  distributions: "sdist bdist_wheel bdist_egg"


